version: '2.1'
services:
  # haproxy:
  #   image: haproxy:2.0.5-alpine
  #   volumes:
  #   - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
  #   ports:
  #   - "8404:8404"
  #   - "9009:9009"
  # consul:
  #   image: consul
  #   ports:
  #   - "8500:8500"
  cortex1:
    image: quay.io/cortexproject/cortex:v1.10.0-rc.1
    command: -config.file=/etc/cortex.yaml # -ring.store=consul  -consul.hostname=consul:8500
    ports:
    - "9001:9009"
    volumes:
    - "./cortex.yaml:/etc/cortex.yaml"
  cortex2:
      image: quay.io/cortexproject/cortex:v1.10.0-rc.1
      command: -config.file=/etc/cortex.yaml # -ring.store=consul  -consul.hostname=consul:8500
      ports:
      - "9002:9009"
      volumes:
      - "./cortex.yaml:/etc/cortex.yaml"
  
  prometheus1:
    image: prom/prometheus
    command: --log.level=debug --config.file=/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
    volumes:
    - "./prometheus1.yml:/etc/prometheus/prometheus.yml"
  prometheus2:
    image: prom/prometheus
    command: --log.level=debug --config.file=/etc/prometheus/prometheus.yml
    ports:
    - "9091:9090"
    volumes:
    - "./prometheus2.yml:/etc/prometheus/prometheus.yml"
  remote_read:
    image: prom/prometheus
    command: --log.level=debug --config.file=/etc/prometheus/prometheus.yml
    ports:
    - "9092:9090"
    volumes:
    - "./remote_read.yml:/etc/prometheus/prometheus.yml"
  promxy:
    image: quay.io/jacksontj/promxy:master
    command: --config=/etc/promxy/promxy.yml
    ports:
    - "8082:8082"
    volumes:
    - "./promxy.yml:/etc/promxy/promxy.yml"

  # sigv4:
  #   image: public.ecr.aws/aws-observability/aws-sigv4-proxy:1.0
  #   environment:
  #   - AWS_ACCESS_KEY_ID=
  #   - AWS_SECRET_ACCESS_KEY=
  #   command: --name=aps --region=us-west-2 --host="aps-workspaces.us-west-2.amazonaws.com" --port=":8005"
  #   # build:
  #   #   context: .
  #   #   args:
  #   #     --name: aps
  #   #     --region: us-west-2
  #   #     --host: aps-workspaces.us-west-2.amazonaws.com
  #   #     --port: :8005
  #   ports:
  #   - "8005:8005"
